import {
  type Icon,
  ChartBarIcon,
  CodeIcon,
  FileTextIcon,
  PaletteIcon,
  PhoneIcon,
  RocketIcon,
  LightningIcon,
  GlobeIcon,
  LayoutIcon,
  DatabaseIcon,
  HardDrivesIcon,
  ShieldIcon,
  GearSixIcon,
  MonitorIcon,
  DeviceMobileIcon,
  CloudIcon,
  GitBranchIcon,
  TerminalIcon,
  CpuIcon,
  HardDriveIcon,
  WifiHighIcon,
  LockIcon,
  KeyIcon,
  EnvelopeSimpleIcon,
  ChatCircleIcon,
  UsersIcon,
  ShoppingCartIcon,
  CreditCardIcon,
  TrendUpIcon,
  ChartPieIcon,
  PulseIcon,
  MagnifyingGlassIcon,
  FunnelIcon,
  StackIcon,
  PackageIcon,
  CubeIcon,
  TreeStructureIcon,
  GearIcon,
  WrenchIcon,
  HammerIcon,
  PenNibIcon,
  FigmaLogoIcon,
  ImageIcon,
  VideoCameraIcon,
  MusicNoteIcon,
  BookOpenIcon,
  GraduationCapIcon,
  LightbulbIcon,
  TargetIcon,
  TrophyIcon,
  StarIcon,
  HeartIcon,
  ThumbsUpIcon,
  ClockIcon,
  CalendarBlankIcon,
  MapPinIcon,
  NavigationArrowIcon,
  PaperPlaneTiltIcon,
  DownloadSimpleIcon,
  UploadSimpleIcon,
  ArrowsClockwiseIcon,
  RepeatIcon,
  PlayIcon,
  PauseIcon,
  CheckCircleIcon,
  XCircleIcon,
  WarningIcon,
  InfoIcon,
  QuestionIcon,
  EyeIcon,
  EyeSlashIcon,
  ArrowsOutIcon,
  ArrowsInIcon,
  ArrowsOutCardinalIcon,
  CopyIcon,
  ScissorsIcon,
  ClipboardIcon,
  LinkIcon,
  ArrowSquareOutIcon,
  ShareNetworkIcon,
  BookmarkSimpleIcon,
  FlagIcon,
  BellIcon,
  BellRingingIcon,
  MegaphoneIcon,
  BroadcastIcon,
  HeadphonesIcon,
  CameraIcon,
  ApertureIcon,
  SparkleIcon,
  FireIcon,
  DropIcon,
  SunIcon,
  MoonIcon,
  CloudRainIcon,
  WindIcon,
  SnowflakeIcon,
  LeafIcon,
  TreeEvergreenIcon,
  MountainsIcon,
  CompassIcon,
  MapTrifoldIcon,
  AirplaneTiltIcon,
  CarIcon,
  BicycleIcon,
  BoatIcon,
  TrainIcon,
  BusIcon,
  BuildingsIcon,
  HouseIcon,
  StorefrontIcon,
  BankIcon,
  FactoryIcon,
  WarehouseIcon,
  BriefcaseIcon,
  CurrencyDollarIcon,
  CurrencyEurIcon,
  CurrencyBtcIcon,
  CoinsIcon,
  ReceiptIcon,
  TableIcon,
  PresentationIcon,
  ChartLineIcon,
  GaugeIcon,
  ThermometerIcon,
  ScalesIcon,
  RulerIcon,
  PencilSimpleIcon,
  EraserIcon,
  PaintBrushIcon,
  TextTIcon,
  TextBIcon,
  TextItalicIcon,
  TextUnderlineIcon,
  TextAlignLeftIcon,
  TextAlignCenterIcon,
  TextAlignRightIcon,
  ListIcon,
  ListNumbersIcon,
  GridFourIcon,
  SquaresFourIcon,
  SidebarSimpleIcon,
  RowsIcon,
  PuzzlePieceIcon,
  FingerprintIcon,
  QrCodeIcon,
  BarcodeIcon,
  HashIcon,
  AtIcon,
  PercentIcon,
  InfinityIcon,
  BracketsCurlyIcon,
  BracketsSquareIcon,
  CodeSimpleIcon,
  FileCodeIcon,
  BugIcon,
  TestTubeIcon,
  FlaskIcon,
  DnaIcon,
  AtomIcon,
  PlanetIcon,
  BinocularsIcon,
} from "@phosphor-icons/react";

const iconMap: Record<string, Icon> = {
  BarChart3: ChartBarIcon,
  Code: CodeIcon,
  FileCheck: FileTextIcon,
  Palette: PaletteIcon,
  Phone: PhoneIcon,
  Rocket: RocketIcon,
  Zap: LightningIcon,
  Globe: GlobeIcon,
  Layout: LayoutIcon,
  Database: DatabaseIcon,
  Server: HardDrivesIcon,
  Shield: ShieldIcon,
  Settings: GearSixIcon,
  Monitor: MonitorIcon,
  Smartphone: DeviceMobileIcon,
  Cloud: CloudIcon,
  GitBranch: GitBranchIcon,
  Terminal: TerminalIcon,
  Cpu: CpuIcon,
  HardDrive: HardDriveIcon,
  Wifi: WifiHighIcon,
  Lock: LockIcon,
  Key: KeyIcon,
  Mail: EnvelopeSimpleIcon,
  MessageSquare: ChatCircleIcon,
  Users: UsersIcon,
  ShoppingCart: ShoppingCartIcon,
  CreditCard: CreditCardIcon,
  TrendingUp: TrendUpIcon,
  PieChart: ChartPieIcon,
  Activity: PulseIcon,
  Search: MagnifyingGlassIcon,
  Filter: FunnelIcon,
  Layers: StackIcon,
  Package: PackageIcon,
  Boxes: CubeIcon,
  Workflow: TreeStructureIcon,
  Cog: GearIcon,
  Wrench: WrenchIcon,
  Hammer: HammerIcon,
  PenTool: PenNibIcon,
  Figma: FigmaLogoIcon,
  Image: ImageIcon,
  Video: VideoCameraIcon,
  Music: MusicNoteIcon,
  FileText: FileTextIcon,
  BookOpen: BookOpenIcon,
  GraduationCap: GraduationCapIcon,
  Lightbulb: LightbulbIcon,
  Target: TargetIcon,
  Award: TrophyIcon,
  Star: StarIcon,
  Heart: HeartIcon,
  ThumbsUp: ThumbsUpIcon,
  Clock: ClockIcon,
  Calendar: CalendarBlankIcon,
  MapPin: MapPinIcon,
  Navigation: NavigationArrowIcon,
  Send: PaperPlaneTiltIcon,
  Download: DownloadSimpleIcon,
  Upload: UploadSimpleIcon,
  RefreshCw: ArrowsClockwiseIcon,
  Repeat: RepeatIcon,
  Play: PlayIcon,
  Pause: PauseIcon,
  CheckCircle: CheckCircleIcon,
  XCircle: XCircleIcon,
  AlertTriangle: WarningIcon,
  Info: InfoIcon,
  HelpCircle: QuestionIcon,
  Eye: EyeIcon,
  EyeOff: EyeSlashIcon,
  Maximize: ArrowsOutIcon,
  Minimize: ArrowsInIcon,
  Move: ArrowsOutCardinalIcon,
  Copy: CopyIcon,
  Scissors: ScissorsIcon,
  Clipboard: ClipboardIcon,
  Link: LinkIcon,
  ExternalLink: ArrowSquareOutIcon,
  Share: ShareNetworkIcon,
  Bookmark: BookmarkSimpleIcon,
  Flag: FlagIcon,
  Bell: BellIcon,
  BellRing: BellRingingIcon,
  Megaphone: MegaphoneIcon,
  Radio: BroadcastIcon,
  Headphones: HeadphonesIcon,
  Camera: CameraIcon,
  Aperture: ApertureIcon,
  Sparkles: SparkleIcon,
  Flame: FireIcon,
  Droplet: DropIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  CloudRain: CloudRainIcon,
  Wind: WindIcon,
  Snowflake: SnowflakeIcon,
  Leaf: LeafIcon,
  TreePine: TreeEvergreenIcon,
  Mountain: MountainsIcon,
  Compass: CompassIcon,
  Map: MapTrifoldIcon,
  Plane: AirplaneTiltIcon,
  Car: CarIcon,
  Bike: BicycleIcon,
  Ship: BoatIcon,
  Train: TrainIcon,
  Bus: BusIcon,
  Building: BuildingsIcon,
  Home: HouseIcon,
  Store: StorefrontIcon,
  Landmark: BankIcon,
  Factory: FactoryIcon,
  Warehouse: WarehouseIcon,
  Briefcase: BriefcaseIcon,
  DollarSign: CurrencyDollarIcon,
  Euro: CurrencyEurIcon,
  Bitcoin: CurrencyBtcIcon,
  Coins: CoinsIcon,
  Receipt: ReceiptIcon,
  FileSpreadsheet: TableIcon,
  Presentation: PresentationIcon,
  ChartBar: ChartBarIcon,
  ChartLine: ChartLineIcon,
  ChartPie: ChartPieIcon,
  Gauge: GaugeIcon,
  Thermometer: ThermometerIcon,
  Scale: ScalesIcon,
  Ruler: RulerIcon,
  Pencil: PencilSimpleIcon,
  Eraser: EraserIcon,
  Paintbrush: PaintBrushIcon,
  PaletteIcon: PaletteIcon,
  Brush: PaintBrushIcon,
  Type: TextTIcon,
  Bold: TextBIcon,
  Italic: TextItalicIcon,
  Underline: TextUnderlineIcon,
  AlignLeft: TextAlignLeftIcon,
  AlignCenter: TextAlignCenterIcon,
  AlignRight: TextAlignRightIcon,
  List: ListIcon,
  ListOrdered: ListNumbersIcon,
  Table: TableIcon,
  Grid3X3: GridFourIcon,
  LayoutDashboard: SquaresFourIcon,
  Sidebar: SidebarSimpleIcon,
  PanelLeft: SidebarSimpleIcon,
  SplitSquareVertical: RowsIcon,
  Columns3: GridFourIcon,
  Rows3: RowsIcon,
  Component: PuzzlePieceIcon,
  Puzzle: PuzzlePieceIcon,
  Blocks: CubeIcon,
  CircuitBoard: CpuIcon,
  Fingerprint: FingerprintIcon,
  ScanFace: FingerprintIcon,
  QrCode: QrCodeIcon,
  Barcode: BarcodeIcon,
  Hash: HashIcon,
  AtSign: AtIcon,
  Percent: PercentIcon,
  Infinity: InfinityIcon,
  Pi: HashIcon,
  Sigma: HashIcon,
  Binary: CodeIcon,
  Braces: BracketsCurlyIcon,
  Brackets: BracketsSquareIcon,
  Code2: CodeSimpleIcon,
  FileCode: FileCodeIcon,
  Bug: BugIcon,
  TestTube: TestTubeIcon,
  Flask: FlaskIcon,
  Beaker: FlaskIcon,
  Microscope: MagnifyingGlassIcon,
  Dna: DnaIcon,
  Atom: AtomIcon,
  Orbit: PlanetIcon,
  Satellite: PlanetIcon,
  Telescope: BinocularsIcon,
  RocketIcon: RocketIcon,
};

export function getIcon(name: string): Icon {
  return iconMap[name] || CodeIcon;
}

export function getIconNames(): string[] {
  return Object.keys(iconMap);
}

export { iconMap };
export type { Icon };
